# Generated by Django 5.2.12 on 2026-04-26 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
    ('cases', '0001_initial'),  # Cambió de '0004_notification_related_entry_and_more'
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='CaseAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la cita')),
                ('scheduled_for', models.DateTimeField(verbose_name='Fecha y hora de la cita')),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('ATE', 'Atendida'), ('NAS', 'No asistió'), ('REP', 'Reprogramada'), ('CAN', 'Cancelada')], default='PEN', max_length=3, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cases.case', verbose_name='Caso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Cita de caso',
                'verbose_name_plural': 'Citas de caso',
                'ordering': ['scheduled_for'],
            },
        ),
    ]
