# Generated by Django 5.2.12 on 2026-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_caseappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closure_process_type',
            field=models.CharField(choices=[('TUT', 'Tutela'), ('PRO', 'Proceso judicial')], default='PRO', max_length=3, verbose_name='Tipo de asunto de cierre'),
        ),
        migrations.AddField(
            model_name='case',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('DES_TAC', 'Desistimiento tácito del usuario'), ('DES_EXP', 'Desistimiento expreso del usuario'), ('GAN', 'Caso finalizado jurídicamente (ganado)'), ('PER', 'Caso finalizado jurídicamente (perdido)'), ('INF_TER', 'Infringió los términos del consultorio jurídico')], max_length=10, null=True, verbose_name='Motivo de cierre'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, choices=[('PEN', 'Sala penal'), ('LAB', 'Sala laboral'), ('CIV', 'Sala civil'), ('FAM', 'Sala familia'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=10, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='case',
            name='closure_type',
            field=models.CharField(blank=True, choices=[('FAV', 'A favor'), ('NEG', 'En contra'), ('DIS', 'Desistido')], help_text='Solo se llena cuando el caso se cierra', max_length=10, null=True, verbose_name='Tipo de cierre'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='case_category',
            field=models.CharField(choices=[('PEN', 'Sala penal'), ('LAB', 'Sala laboral'), ('CIV', 'Sala civil'), ('FAM', 'Sala familia'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=10, verbose_name='Categoría de caso'),
        ),
    ]
