# Generated by Django 5.2.12 on 2026-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_closure_process_type_case_closure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type_specific',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Trámite jurídico'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, choices=[('PEN', 'Sala penal'), ('LAB', 'Sala laboral'), ('CIV', 'Sala civil'), ('FAM', 'Sala familia'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=10, null=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='case_category',
            field=models.CharField(choices=[('PEN', 'Sala penal'), ('LAB', 'Sala laboral'), ('CIV', 'Sala civil'), ('FAM', 'Sala familia'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=10, verbose_name='Sala del caso'),
        ),
    ]
