# Generated by Django 5.2.12 on 2026-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, choices=[('PEN', 'Sala Penal'), ('LAB', 'Sala Laboral'), ('CIV', 'Sala Civil'), ('FAM', 'Sala Familia'), ('DER_PUB_MIG', 'Sala Derecho Público')], max_length=20, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='case_category',
            field=models.CharField(choices=[('PEN', 'Sala Penal'), ('LAB', 'Sala Laboral'), ('CIV', 'Sala Civil'), ('FAM', 'Sala Familia'), ('DER_PUB_MIG', 'Sala Derecho Público')], max_length=20, verbose_name='Categoría de caso'),
        ),
    ]
