# Generated by Django 5.2.12 on 2026-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_case_type_specific_alter_case_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraentry',
            name='event_type',
            field=models.CharField(choices=[('SEG', 'Seguimiento del caso'), ('REU', 'Reunión'), ('AUD', 'Audiencia'), ('TRI', 'Cita de tribunal'), ('VEN', 'Vencimiento de término'), ('DOC', 'Documento o soporte'), ('OTR', 'Otro evento')], default='SEG', max_length=3, verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='starts_new_term',
            field=models.BooleanField(default=False, verbose_name='Empezar a contar nuevo término'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='term_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de vencimiento del término'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='entry_type',
            field=models.CharField(choices=[('ACT', 'Actualización'), ('ENT', 'Entrevista'), ('OBS', 'Observación'), ('ASI', 'Asignación'), ('DOC', 'Documento'), ('EVE', 'Evento'), ('CAS_MAN', 'Caso Asignado Manualmente'), ('CAS_REV', 'Caso Enviado a Revisión')], default='EVE', max_length=10, verbose_name='Clasificación interna'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Enviar notificación por correo'),
        ),
    ]
