# Generated by Django 5.2.12 on 2026-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closure_description',
            field=models.TextField(blank=True, help_text='Descripción detallada del motivo de cierre', null=True, verbose_name='Descripción del cierre'),
        ),
        migrations.AlterField(
            model_name='case',
            name='closure_type',
            field=models.CharField(blank=True, choices=[('DES_TAC', 'Desistimiento tácito del usuario'), ('DES_EXP', 'Desistimiento expreso del usuario'), ('FIN_GAN', 'Caso finalizado jurídicamente (Ganado)'), ('FIN_PER', 'Caso finalizado (perdido)'), ('INF_TER', 'Infringió los términos del consultorio jurídico')], help_text='Solo se llena cuando el caso se cierra', max_length=10, null=True, verbose_name='Tipo de cierre'),
        ),
    ]
