# Generated by Django 5.2.12 on 2026-05-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_bitacoraentry_event_type_and_more'),
        ('cases', '0009_case_closure_description_alter_case_closure_type'),
    ]

    operations = [
    ]
