# Generated by Django 5.2.12 on 2026-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_merge_20260518_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, choices=[('PEN', 'Sala Penal'), ('LAB', 'Sala Laboral'), ('CIV', 'Sala Civil'), ('FAM', 'Sala Familia'), ('DER_PUB_MIG', 'Sala Derecho Público'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=20, null=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='case',
            name='closure_type',
            field=models.CharField(blank=True, choices=[('DES_TAC', 'Desistimiento tácito del usuario'), ('DES_EXP', 'Desistimiento expreso del usuario'), ('FIN_GAN', 'Caso finalizado jurídicamente (Ganado)'), ('FIN_PER', 'Caso finalizado (perdido)'), ('INF_TER', 'Infringió los términos del consultorio jurídico'), ('FAV', 'A favor'), ('NEG', 'En contra'), ('DIS', 'Desistido')], help_text='Solo se llena cuando el caso se cierra', max_length=10, null=True, verbose_name='Tipo de cierre'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('SIN', 'Sin asignar'), ('DOC', 'Documentación'), ('ASI', 'Asignado'), ('AUT', 'Autoasignado'), ('PRO', 'En proceso'), ('ESP', 'Esperar por beneficiario'), ('REV', 'En revisión'), ('CER', 'Cerrado')], default='SIN', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='case_category',
            field=models.CharField(choices=[('PEN', 'Sala Penal'), ('LAB', 'Sala Laboral'), ('CIV', 'Sala Civil'), ('FAM', 'Sala Familia'), ('DER_PUB_MIG', 'Sala Derecho Público'), ('PUB', 'Sala derecho público'), ('MIGR', 'Sala derecho público - Migrantes'), ('ADM', 'Sala administrativa')], max_length=20, verbose_name='Sala del caso'),
        ),
    ]
