# Generated by Django 5.2.12 on 2026-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'No reporta')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='user',
            name='socioeconomic_stratum',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
    ]
